config/routes.rb
Rails.application.routes.draw do
  root to: 'news#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events do
    resource :clubs
    match '/clubs/:id',   to: 'clubs#register_to_event',   via: 'get', :as => :register_to_event
  end
  # devise_scope :user do
  #   get "signup", to: "devise/registrations#new"
  #   get "login", to: "devise/sessions#new"
  #   get "logout", to: "devise/sessions#destroy"
  # end
  resources :news
  resources :users
  delete "users/:id", to: "users#destroy"
  match '/users/makeAdmin/:id',   to: 'users#makeAdmin',   via: 'get', :as => :users_makeAdmin
  match '/users/revokeAdmin/:id',   to: 'users#revokeAdmin',   via: 'get', :as => :users_revokeAdmin
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :omniauthable 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable
  has_many :news
  has_many :events
  has_many :clubs
  has_many :events, through: :clubs
  validates :first_name, :last_name, :dob, :designation, :company, :address, presence: true, length: {minimum: 3}
  validates :gender, presence: true

  def admin_type
    if self.admin?
      "Admin"
    else
      "User"
    end
  end

  def full_name
    self.first_name + " " + self.last_name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def new
    # authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      flash[:success] = "User Updated Successfully"
      redirect_to users_path
    else
      flash.now[:error] = "User is not Updated"
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end
  def destroy
    event = Event.select("event_id").where(user_id: params[:id])
    Club.where(event_id: event).delete_all
    Event.where(user_id: params[:id]).delete_all
    News.where(user_id: params[:id]).delete_all
    Club.where(user_id: params[:id]).delete_all
    @user = User.find(params[:id])
    authorize @user
  
    if @user.destroy
      redirect_to users_path, notice: "User deleted."
    else
      redirect_to users_path, flash: {error: "User could not be deleted." }
    end
  end

  def makeAdmin
    @user = User.find(params[:id])
    authorize @user
    @user.update(admin: true)
    redirect_to users_path
  end

  def revokeAdmin
    @user = User.find(params[:id])
    authorize @user
    @user.update(admin: false)
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :dob, :designation, :company, :address, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for(:title, "Edit Profile") %>
<div class="row">
  <div class="col-md-12 my-3">
    <div class="bg-mattBlackLight px-3 py-3">
      <h2 class="display-5 p-2 text-center">Edit Profile</h2>
      <hr>
      <div class="row mb-2 justify-content-center">
        <div class="col col-md-6  p-4 mb-4">
          <div class="form-group ml-3">
            <% if @user.admin %>
              <%= link_to 'Revoke Admin', users_revokeAdmin_path(id: @user.id), class: "btn btn-primary btn-sm" %>
            <% else %>
              <%= link_to 'Make Admin', users_makeAdmin_path(id: @user.id), class: "btn btn-primary btn-sm" %>
            <% end %>
          </div>
          <%= form_with(model: @user, local: true, validate: true) do |f|  %>
            <div class="form-group">
              <%= f.label :first_name, class:"col-md-4 text-capitalize font-weight-bold"%>
              <div class="col-md-8">
                <%= f.text_field :first_name, class: 'form-control', autofocus: true, required: true %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :last_name, class:"col-md-8 text-capitalize font-weight-bold" %>
              <div class="col-md-8">
                <%= f.text_field :last_name, class: 'form-control', required: true %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :gender, class:"col-md-8 text-capitalize font-weight-bold" %>
              <div class="d-flex flex-row ">
                <div class="col-md-3 ml-4">
                  <%= f.radio_button :gender ,'Female', class: 'form-check-input' %> Female
                </div>
                <div class="col-md-4">
                  <%= f.radio_button :gender ,'Male', class: 'form-check-input' %> Male
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :dob, class:"col-md-4 text-capitalize font-weight-bold", value: "Date of Birth" %>
              <div class="form-inline ml-3">
                <%= f.date_select :dob, { order: [:day, :month, :year], start_year: Date.today.year - 18, end_year: Date.today.year - 100},{class: 'form-control mr-1', required: true} %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :designation, class:"col-md-4 text-capitalize font-weight-bold" %>
              <div class="col-md-8">
                <%= f.text_field :designation, class: 'form-control', required: true %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :company, class:"col-md-4 text-capitalize font-weight-bold" %>
              <div class="col-md-8">
                <%= f.text_field :company, class: 'form-control', required: true %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :address, class:"col-md-4 text-capitalize font-weight-bold" %>
              <div class="col-md-8">
                <%= f.text_field :address, class: 'form-control', required: true %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :email, class:"col-md-4 text-capitalize font-weight-bold" %>
              <div class="col-md-8">
                <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', required: true %>
              </div>
            </div>

            <div class="form-group">
              <%= f.submit "Update", class: "btn btn-success ml-3" %>
              <%= link_to "Cancel", users_path, class:"btn btn-dark float-right" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% content_for(:title, "Members") %>
<div class="row">
  <div class="col-md-12 my-3">
    <div class="bg-mattBlackLight p-3">
      <div class="table-wrapper">
        <div class="table-title">
          <div class="row">
            <div class="col-md-12 text-center p-3">
              <h2 class="text-center">Members</h2>
              <hr>
            </div>
          </div>
        </div>

        <% flash.each do |key, value| %>
          <%= content_tag :div, value, class: "flash #{key}" %>
        <% end %>
        <table class="table table-dark">
          <thead>
          <th>Name</th>
            <th>Email</th>
            <th>Gender</th>
            <th>User Type</th>
            <%if current_user.admin? %>
              <th>Change</th>
              <th>Edit</th>
              <th>Remove</th>
            <%end%>
          </thead>
          <tbody>
            <%@users.each do |user| %>
              <tr>
                <td><%= link_to user.full_name , user_path(user.id) %></td>
                <td><%= user.email %> </td>
                <td><%= user.gender %> </td>
                <td>
                  <%= user.admin_type %>
                </td>
                <%if current_user.admin? %>
                  <td>
                    <% if user.admin %>
                      <%= link_to 'Revoke Admin', users_revokeAdmin_path(id: user.id), class: "btn btn-sm btn-primary btn-sm" %>
                    <% else %>
                      <%= link_to 'Make Admin', users_makeAdmin_path(id: user.id), class: "btn btm-sm btn-primary btn-sm" %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "Edit", edit_user_path(user), :class => 'btn btn-sm btn-success' unless user == current_user%>
                  </td>
                  <td>
                    <%= link_to "Delete", user_path(user), data: {confirm: "Are you sure that you wanna delete this user???" }, method: :delete, :class => 'btn btn-sm btn-danger' unless user == current_user%>
                  </td>
                <%end%>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:title, @user.full_name) %>
<div class="row">
  <div class="col-md-12 my-3">
    <div class="bg-mattBlackLight px-3 py-3">
      <div class="table-wrapper">
          <div class="table-title">
              <div class="row">
                  <div class="col-md-10 text-center p-4">
                      <h2 class="text-center">My Profile</h2>
                  </div>
              </div>
          </div>
          <table class="table table-dark">
              <tbody>
                  <tr>
                      <td>Name</td>
                      <td><%= @user.full_name %></td>
                  </tr>
                  <tr>
                      <td>Email</td>
                      <td><%= @user.email %> </td>
                  </tr>
                  <tr>
                      <td>Gender</td>
                      <td><%= @user.gender %> </td>
                  </tr>
                  <tr>
                      <td>Date of Birth</td>
                      <td><%= @user.dob %> </td>
                  </tr>
                  <tr>
                      <td>Designation</td>
                      <td><%= @user.designation %> </td>
                  </tr>
                  <tr>
                      <td>Company</td>
                      <td><%= @user.company %> </td>
                  </tr>
                      <tr>
                      <td>Address</td>
                      <td><%= @user.address %> </td>
                  </tr>

                  <tr>
                      <td>Admin Type</td>
                      <td>
                          <%= @user.admin_type %>
                      </td>
                  <tr>
              </tbody>
          </table>
          <div class="row">
            <div class="col-md-12">
              <% if current_user == @user%>
                <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-info float-right" %>
               <%elsif current_user.admin? %>
                <%= link_to "Edit User", edit_user_path(@user.id), class:"btn btn-info float-right" %>
              <%end %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>