config/routes.rb
Rails.application.routes.draw do
  root to: 'news#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events do
    resource :clubs
    match '/clubs/:id',   to: 'clubs#register_to_event',   via: 'get', :as => :register_to_event
  end
  # devise_scope :user do
  #   get "signup", to: "devise/registrations#new"
  #   get "login", to: "devise/sessions#new"
  #   get "logout", to: "devise/sessions#destroy"
  # end
  resources :news
  resources :users
  delete "users/:id", to: "users#destroy"
  match '/users/makeAdmin/:id',   to: 'users#makeAdmin',   via: 'get', :as => :users_makeAdmin
  match '/users/revokeAdmin/:id',   to: 'users#revokeAdmin',   via: 'get', :as => :users_revokeAdmin
end

app/models/event.rb
class Event < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :clubs
    has_many :users, through: :clubs
    validates :description, presence: true, length: { minimum: 32 }
    validates :name, uniqueness: true, presence: true, length: { minimum: 3 }
    validates :event_date, :start_time, :end_time, presence: true
    validate :image_valid
    validate :time_validate
    # validates :image, attached: true

    def time_start
        self.start_time.to_s(:time)
    end

    def time_end
        self.end_time.to_s(:time)
    end

    def event_categorize
        # binding.pry
        if event_date.past?
            "past"
        elsif event_date.future?
            "upcoming"
        else
            if start_time.strftime( "%H%M%S%N" ) > Time.now.strftime( "%H%M%S%N" )
                return "upcoming"
            elsif end_time.strftime( "%H%M%S%N" ) < Time.now.strftime( "%H%M%S%N" )
                return "past"
            else
                return "current"
            end
        end
    end

    private
    def image_valid
        if !image.attached?
            errors.add(:image, "Image Required.")
        elsif !image.content_type.in?(%w(image/jpeg image/png image/jpg))
            errors.add(:image, "must be a JPEG, JPG or PNG.")
        end  
    end

    def time_validate
        if start_time.to_i>=end_time.to_i
            errors.add(:end_time, "End Time should greater than Start Time")
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_authorized

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order("event_date DESC")
    @registered_events = Club.where(user_id: current_user).order("created_at DESC")
    authorize @events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    authorize @event
    @clubs = Club.where(" event_id= ? AND user_id= ?", params[:id].to_i, current_user)
  end

  # GET /events/new
  def new
    @event = Event.new
    authorize @event
  end

  # GET /events/1/edit
  def edit
    authorize @event
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    authorize @event
    @event.user = current_user
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    authorize @event
    respond_to do |format|
      if @event.update(event_params)
        @users = Club.where(" event_id= ? ", @event.id)
        NotificationMailer.send_notification(@event, @users)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    authorize @event
    Club.where(event_id: params[:id]).delete_all
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :image, :event_date, :start_time, :end_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, validate: true) do |form| %>
  <%
=begin%>
 <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 
<%
=end%>

  <div class="form-group">
    <%= form.label :name, class:"col-md-4 text-capitalize font-weight-bold", value: "Event Name" %>
    <div class="col-md-10">
      <%= form.text_field :name, class: 'form-control', placeholder: 'What is the name of the Event?', required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, class:"col-md-4 text-capitalize font-weight-bold" %>
    <%= form.hidden_field :description, id: "post_event" %>
    <div class="col-md-12">
      <trix-editor input="post_event", class='form-control border border-secondary trix-editor'></trix-editor>
    </div>
  </div>
  
  <div class="form-group">
    <%= form.label :image, class:"col-md-4 text-capitalize font-weight-bold", value: "Upload Image" %>
    <div class="col-md-10">
      <%= form.file_field :image%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :event_date, class:"col-md-4 text-capitalize font-weight-bold" %>
    <div class="form-inline ml-3">
      <%= form.date_select :event_date, { order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year+10},{class: 'form-control mr-1', required: true} %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :start_time, class:"col-md-4 text-capitalize font-weight-bold" %>
    <div class="form-inline ml-3">
      <%= form.time_select :start_time, {}, {class: 'form-control mr-1', required: true} %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :end_time, class:"col-md-4 text-capitalize font-weight-bold" %>
    <div class="form-inline ml-3">
      <%= form.time_select :end_time,{}, {class: 'form-control mr-1', required: true} %>
    </div>
  </div>

  <div class="form-group col-md-12 mt-5">
    <%= form.submit class: "btn btn-success ml-3 float-right" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% content_for(:title, "Edit Event") %>
<div class="row">
  <div class="col-md-12 my-3">
    <div class="bg-mattBlackLight px-3 py-3">
      <h2 class="display-5 p-4 text-center">Edit Event</h2>
      <div class="row mb-2 justify-content-center">
          <div class="col col-md-8 shadow-lg p-4 mb-4">
              <%= render 'form', event: @event %>class
              <%= link_to 'Back', events_path, class: "btn btn-danger ml-3" %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<% content_for(:title, "Events")%>
<div class="row">
  <div class="col-md-12 my-3">
    <div class="bg-mattBlackLight px-3 py-3">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <h4 class="mb-2 text-center">Events</h4>
        </div>
        <div class="col-md-3">
          <%if current_user.admin? %>
            <%= link_to 'Add New Event', new_event_path, class: "btn btn-dark ml-3 float-right" %>
          <%end%>
        </div>
      </div>
      <hr>
      <p id="notice"><%= notice %></p>
      <!-- Nav tabs -->
      <ul class="nav nav-tabs">
        <li class="nav-item col-3">
          <a class="nav-link active" data-toggle="tab" href="#upcoming">Upcoming Events</a>
        </li>
        <li class="nav-item col-3">
          <a class="nav-link" data-toggle="tab" href="#past">Past Events </a>
        </li>
        <li class="nav-item col-3">
          <a class="nav-link" data-toggle="tab" href="#current">Current Events</a>
        </li>
        <li class="nav-item col-3">
          <a class="nav-link" data-toggle="tab" href="#registered">Registered Events</a>
        </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <div class="tab-pane container active" id="upcoming">
          <div class="row bg-mattBlackLight my-3 justify-content-center">
            <div class="col-12">
              <% @events.each do |event| %>
                <% if event.event_categorize == "upcoming" %>
                  <div class="row align-content-center">
                    <div class="col-5 p-3">
                      <%= image_tag(event.image, class:"img-fluid", alt:"Responsive image",
                                    width:"350", height:"250")%>
                    </div>
                    <div class="col-7">
                      <h6 class="text-capitalize font-weight-bold text-center border-bottom p-2"><%= link_to event.name,  event %> </h6>
                      <span class="mt-1">
                        <% if event.description.length > 350 %>
                          <%= truncate(sanitize(event.description, :tags => %w()), :length => 350)  %><%= link_to 'Read more', event %>
                        <% else %>
                          <%= sanitize event.description %>
                        <% end %>
                      </span>
                      <hr>
                      <%= link_to 'Show', event %>
                      <%if current_user.admin? %>
                        <%= link_to 'Edit', edit_event_path(event) %>
                        <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <%end%>
                      <div class="float-right text-capitalize"><%= event.user.full_name %> | Created <%= time_ago_in_words(event.created_at) %> </div>
                    </div>
                  </div>
                  <hr>
                  Date: <%= event.event_date %> | Start From: <%= event.time_start %> | End At: <%= event.time_end %>
                  <hr>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="tab-pane container fade" id="past">
          <div class="row bg-mattBlackLight my-3 justify-content-center">
            <div class="col-12">
              <% @events.each do |event| %>
                <% if event.event_categorize == "past" %>
                  <div class="row align-content-center">
                    <div class="col-5 p-3">
                      <%= image_tag(event.image, class:"img-fluid", alt:"Responsive image",
                                    width:"350", height:"250")%>
                    </div>
                    <div class="col-7">
                      <h6 class="text-capitalize font-weight-bold text-center border-bottom p-2"><%= link_to event.name,  event %> </h6>
                      <span class="mt-1">
                        <% if event.description.length > 350 %>
                          <%= truncate(sanitize(event.description, :tags => %w()), :length => 350)  %><%= link_to 'Read more', event %>
                        <% else %>
                          <%= sanitize event.description %>
                        <% end %>
                      </span>
                      <hr>
                      <%= link_to 'Show', event %>
                      <%if current_user.admin? %>
                        <%= link_to 'Edit', edit_event_path(event) %>
                        <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <%end%>
                      <div class="float-right text-capitalize"><%= event.user.full_name %> | Created <%= time_ago_in_words(event.created_at) %> </div>
                    </div>
                  </div>
                  <hr>
                  Date: <%= event.event_date %> | Start From: <%= event.time_start %> | End At:<%= event.time_end %>
                  <hr>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="tab-pane container fade" id="current">
          <div class="row my-3 bg-mattBlackLight justify-content-center">
            <div class="col-12">
              <% @events.each do |event| %>
                <% if event.event_categorize == "current" %>
                  <div class="row align-content-center">
                    <div class="col-5 p-3">
                      <%= image_tag(event.image, class:"img-fluid", alt:"Responsive image",
                                    width:"350", height:"250")%>
                    </div>
                    <div class="col-7">
                      <h6 class="text-capitalize font-weight-bold text-center border-bottom p-2"><%= link_to event.name,  event %> </h6>
                      <span class="mt-1">
                        <% if event.description.length > 350 %>
                          <%= truncate(sanitize(event.description, :tags => %w()), :length => 350)  %><%= link_to 'Read more', event %>
                        <% else %>
                          <%= sanitize event.description %>
                        <% end %>
                      </span>
                      <hr>
                      <%= link_to 'Show', event %>
                      <%if current_user.admin? %>
                        <%= link_to 'Edit', edit_event_path(event) %>
                        <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <%end%>
                      <div class="float-right text-capitalize"><%= event.user.full_name %> | Created <%= time_ago_in_words(event.created_at) %> </div>
                    </div>
                  </div>
                  <hr>
                  Date: <%= event.event_date %> | Start From: <%= event.time_start %> | End At:<%= event.time_end %>
                  <hr>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="tab-pane container fade" id="registered">
          <div class="tab-pane container active" id="upcoming">
            <div class="row my-3 bg-mattBlackLight justify-content-center">
              <div class="col-12">
                <% @registered_events.each do |c| %>
                  <div class="row align-content-center">
                    <div class="col-5 p-3">
                      <%= image_tag(c.event.image, class:"img-fluid", alt:"Responsive image",
                                    width:"350", height:"250")%>
                    </div>
                    <div class="col-7">
                      <h6 class="text-capitalize font-weight-bold text-center border-bottom p-2">
                        <%= link_to c.event.name,   event_path(id: c.event_id) %>
                      </h6>
                      <span class="mt-1">
                        <% if c.event.description.length > 350 %>
                          <%= truncate(sanitize(c.event.description, :tags => %w()), :length => 350)  %>
                                  <%= link_to 'Read more', event_path(id: c.event_id) %>
                        <% else %>
                          <%= sanitize c.event.description %>
                        <% end %>
                      </span>
                      <hr>
                      <%= link_to 'Show', event_path(id: c.event_id) %>
                      <%if current_user.admin? %>
                        <%= link_to 'Edit', edit_event_path(c.event_id) %>
                        <%= link_to 'Destroy', event_path(id: c.event), method: :delete, data: { confirm: 'Are you sure?' } %>
                      <%end%>

                      <div class="float-right text-capitalize"><%= c.event.user.full_name %> | Created <%= time_ago_in_words(c.event.created_at) %> </div>
                    </div>
                  </div>
                  <hr>
                  Date: <%= c.event.event_date %> | Start From: <%= c.event.time_start %> | End At:<%= c.event.time_end %>
                  <hr>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<% content_for(:title, "Add Event")%>
<div class="row">
  <div class="col-md-12 my-3">
    <div class="bg-mattBlackLight px-3 py-3">
      <h2 class="display-5 p-4 text-center">Add New News</h2>
      <div class="row mb-2 justify-content-center">
          <div class="col col-md-8 shadow-lg p-4 mb-4">
              <%= render 'form', event: @event %>
              <%= link_to 'Back', events_path, class: "btn btn-danger ml-3" %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% content_for(:title, "#{@event.name}")%>
<div class="row">
  <div class="col-md-12 my-3">
    <p id="notice"><%= notice %></p>
    <div class="bg-mattBlackLight px-3 py-3">
      <div class="row mb-2 justify-content-center">
        <div class="col-8 shadow">
          <h4 class="text-capitalize font-weight-bold text-center border-bottom pt-3 pb-1 "><%= @event.name %> </h4>
          <div class="row pr-5 pb-5">
            <div class="col-md-12 text-right mt-1">
              <%if  current_user.admin? %>
                <%= link_to 'View Member', event_clubs_path(@event), class: "btn btn-dark ml-3 float-right" %>
              <%end%>
              <%if @event.event_categorize == "upcoming" %>
                <%if  current_user.admin? %>
                  <%= link_to 'Add Member', new_event_clubs_path(@event), class: "btn btn-primary ml-3 float-right" %>
                <%end%>
                <%if @clubs.empty?%>
                  <%= link_to 'Register', event_register_to_event_path(event_id: @event,user_id: @current_user), class: "btn btn-info ml-3 float-right" %>
                <%else%>
                  <%= link_to "De-register", event_clubs_path(id: @clubs[0],event_id: @event), data: { confirm: "Are you sure that you wanna De-register???" }, method: :delete, :class => 'btn btn-danger' %>
                <%end%>
              <%end%>
            </div>
          </div>
          <div class="row pr-5 pb-5">
            <div class="col-md-12">
              <div class="p-3 text-center">
                <%= image_tag(@event.image, class:"image_view img-fluid")%>
              </div>
              <div class="p-3">
                <%= sanitize @event.description %>
              </div>
              <p>
                <strong>Event date:</strong>
                <%= @event.event_date %>
              </p>

              <p>
                <strong>Start time:</strong>
                <%= @event.time_start %>
              </p>

              <p>
                <strong>End time:</strong>
                <%= @event.time_end %>
              </p>
              <hr>
              <div class="row">
                <div class="col-md-12">
                  <%if current_user.admin? %>
                    <%= link_to 'Edit', edit_event_path(@event) , class: "btn btn-success float-right"%>
                  <%end%>
                  <%= link_to 'Back', events_path, class: "btn btn-danger float-left" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>