config/routes.rb
Rails.application.routes.draw do
  root to: 'news#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events do
    resource :clubs
    match '/clubs/:id',   to: 'clubs#register_to_event',   via: 'get', :as => :register_to_event
  end
  # devise_scope :user do
  #   get "signup", to: "devise/registrations#new"
  #   get "login", to: "devise/sessions#new"
  #   get "logout", to: "devise/sessions#destroy"
  # end
  resources :news
  resources :users
  delete "users/:id", to: "users#destroy"
  match '/users/makeAdmin/:id',   to: 'users#makeAdmin',   via: 'get', :as => :users_makeAdmin
  match '/users/revokeAdmin/:id',   to: 'users#revokeAdmin',   via: 'get', :as => :users_revokeAdmin
end

app/models/news.rb
class News < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    validates :body, presence: true, length: { minimum: 32 }
    validates :title, uniqueness: true, presence: true, length: { minimum: 3 }
    validate :image_valid

    private
    def image_valid
        if !image.attached?
            errors.add(:image, "Image Required.")
        elsif !image.content_type.in?(%w(image/jpeg image/png image/jpg))
            errors.add(:image, "must be a JPEG, JPG or PNG.")
        end  
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @news = News.all.order("created_at DESC")
    # render json: @news
    authorize @news
  end

  def show
    authorize @news
  end

  def new
    @news = News.new
    authorize @news
  end

  def edit
    authorize @news
  end

  def create
    @news = News.new(news_params)
    authorize @news
    @news.user = current_user
    respond_to do |format|
      if @news.save
        @users = User.all
        NotificationMailer.send_mail(@news, @users)
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @news
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    authorize @news
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private

    def set_news
      @news = News.find(params[:id])
    end

    def news_params
      params.require(:news).permit(:title, :body, :image)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true, validate: true) do |form| %>
  <div class="form-group">
    <%= form.label :title, class:"col-md-4 text-capitalize font-weight-bold" %>
    <div class="col-md-10">
      <%= form.text_field :title, class: 'form-control', placeholder: 'What is the Title of the News?', required: true%>
    </div>
  </div>

  <div class="form-group ">
    <%= form.label :body, class:"col-md-4 text-capitalize font-weight-bold", value: "Description" %>
    <%= form.hidden_field :body, id: "post_body" %>
    <div class="col-md-12">
      <trix-editor input="post_body", class='form-control border border-secondary trix-editor'></trix-editor>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :image, class:"col-md-4 text-capitalize font-weight-bold", value: "Upload Image" %>
    <div class="col-md-10">
      <%= form.file_field :image%>
    </div>
  </div>
  <div class="form-group col-md-12 mt-5">
    <%= form.submit class: "btn btn-success ml-3 float-right" %>
  </div>
<% end %>

app/views/news/edit.html.erb
<% content_for(:title, "Edit News") %>
<div class="row">
  <div class="col-md-12 my-3">
      <div class="bg-mattBlackLight px-3 py-3">
      <h2 class="display-5 p-4 text-center">Edit News</h2>
      <div class="row mb-2 justify-content-center">
          <div class="col col-md-8 shadow-lg p-4 mb-4">
              <%= render 'form', news: @news %>
              <%= link_to 'Cancel', news_index_path, class: "btn btn-danger ml-3" %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/news/index.html.erb
<% content_for(:title, "News")%>
<div class="row">
  <div class="col-md-12 my-3">
    <div class="bg-mattBlackLight px-3 py-3">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <h4 class="mb-2 text-center">News</h4>
        </div>
        <div class="col-md-3">
          <%if current_user.admin? %>
            <%= link_to 'Add New News', new_news_path, class: "btn btn-dark  border ml-2 float-right" %>
          <%end%>
        </div>
      </div>
      <hr>
      <p id="notice"><%= notice %></p>
      <% @news.each do |news| %>
        <div class="row align-content-center">
          <div class="col-4 p-3">
            <%= image_tag(news.image, class:"img-fluid", alt:"Responsive image",
                          width:"300", height:"100") %>
          </div>
          <div class="col-8">
            <h5 class="text-capitalize text-center border-bottom p-2"><%= link_to news.title, news %> </h5>
            <span class="mt-1">
              <% if news.body.length > 350 %>
                <%= truncate(sanitize(news.body, :tags => %w()), :length => 350)  %><%= link_to 'Read more', news %>
              <% else %>
                <%= sanitize news.body %>
              <% end %>
            </span>
            <hr>
            <%= link_to 'Show', news, class: "btn btn-sm btn-info" %>
            <%if current_user.admin?%>
              <%= link_to 'Edit', edit_news_path(news), class: "btn btn-sm btn-success"%>
              <%= link_to 'Remove', news, class: "btn btn-sm btn-danger" , method: :delete, data: { confirm: 'Are you sure?' } %>
            <%end%>
            <div class="float-right text-capitalize"><%= news.user.full_name %> | Created <%= time_ago_in_words(news.created_at) %> ago</div>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/news/new.html.erb
<% content_for(:title, "Add News")%>

<div class="row">
  <div class="col-md-12 my-3">
    <div class="bg-mattBlackLight px-3 py-3">
      <h2 class="display-5 p-4 text-center">Add New news</h2>
      <div class="row mb-2 justify-content-center">
          <div class="col col-md-8 shadow-lg p-4 mb-4">
              <%= render 'form', news: @news %>
              <%= link_to 'Cancel', news_index_path, class: "btn btn-danger ml-3" %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/news/show.html.erb
<% content_for(:title, "#{@news.title}")%>
<div class="row">
  <div class="col-md-12 my-3">
    <p id="notice"><%= notice %></p>
    <div class="bg-mattBlackLight px-3 py-3">
      <div class="row mb-2 justify-content-center">
        <div class="col-8">
          <h4 class="text-capitalize text-center border-bottom p-3"><%= @news.title %> </h4>
          <div class="p-3 text-center">
            <%= image_tag(@news.image, class:"image_view img-fluid")%>
          </div>
          <div class="p-3">
            <%= sanitize @news.body %>
          </div>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-md-8 border-top pt-3">
          <%if current_user.admin? %>
            <%= link_to 'Edit', edit_news_path(@news), class: "btn btn-success float-right" %>
          <%end%>
          <%= link_to 'Back', news_index_path, class: "btn btn-info float-left"%>
        </div>
      </div>
    </div>
  </div>
</div>